name: Images
version: 2.3.2
main: com.andavin.images.Images
authors: [ 'Andavin' ]
description: A plugin to load and render images on maps.
website: images.andavin.com
softdepend: [ 'Multiverse-Core', 'PlotSquared' ]
depend:
  - ProtocolLib
api-version: '1.13'
folia-supported: true
commands:
  image:
    description: 'Manage custom images.'
    usage: '/<command> [create|delete|list|import]'
    aliases: [ 'customimage', 'images', 'img' ]